### PR TITLE
fix/race: Try to fix a race in oxy

### PR DESCRIPTION
**Pull request by CyrilPeponnet**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by CyrilPeponnet** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1196",
    "commit-sha": "1152e29b078b92c49612d70f3016fddbd985cb4b",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "bahamut",
    "pr-id": "136",
    "commit-sha": "2347ce01d83dd09ef95d6e1ec8527014bdfba228",
    "pipeline": "master"
  }
]
```

**Comment by CyrilPeponnet** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1192",
    "commit-sha": "11366a41b9b49bfce68398bd692831e9b9431032",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "bahamut",
    "pr-id": "136",
    "commit-sha": "2347ce01d83dd09ef95d6e1ec8527014bdfba228",
    "pipeline": "master"
  }
]
```

**Comment by CyrilPeponnet** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1192",
    "commit-sha": "2577f6289473395fd9a9afb9c67e0de6795cf0fc",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "bahamut",
    "pr-id": "136",
    "commit-sha": "b60c2dbaa989476864254f8041bbc6d415078bfa",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "highwind-race-fixes",
    "component": "backend",
    "pr-id": "1199",
    "commit-sha": "c2bd22d71edcc067eb354629bec546e2b9362876",
    "pipeline": "master"
  },
  {
    "project": "highwind-race-fixes",
    "component": "bahamut",
    "pr-id": "136",
    "commit-sha": "b60c2dbaa989476864254f8041bbc6d415078bfa",
    "pipeline": "master"
  },
  {
    "project": "highwind-race-fixes",
    "component": "oxy",
    "pr-id": "6",
    "commit-sha": "d3e4a53bf854dd4eba55b50d7309bdb6df42eac2",
    "pipeline": "master"
  }
]
```

**Comment by CyrilPeponnet** [comment]
replace in lib is not working needs to be done at program level

**Pull request closed without merging**
